version: "3.8"

services:
  app:
    container_name: contest-registration-backend
    build: .
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run local
